name = "fieldpress-api"
main = "src/index.ts"
compatibility_date = "2026-09-02"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[routes]]
pattern = "fieldpress.studio/api*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "www.fieldpress.studio/api*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "app.fieldpress.studio/api*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "fieldpress.studio/s*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "www.fieldpress.studio/s*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "app.fieldpress.studio/s*"
zone_name = "fieldpress.studio"

[[routes]]
pattern = "api.fieldpress.studio/*"
zone_name = "fieldpress.studio"
