// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ClassifiedsWire.tsx": () => import("../components/mockups/ClassifiedsWire.tsx"),
  "./components/mockups/FieldPressApp.tsx": () => import("../components/mockups/FieldPressApp.tsx"),
  "./components/mockups/FieldPressMaster.tsx": () => import("../components/mockups/FieldPressMaster.tsx"),
  "./components/mockups/FieldPressSocial.tsx": () => import("../components/mockups/FieldPressSocial.tsx"),
  "./components/mockups/PressPassCard.tsx": () => import("../components/mockups/PressPassCard.tsx"),
  "./components/mockups/UserProfileView.tsx": () => import("../components/mockups/UserProfileView.tsx")
};
